apiVersion: v1
kind: Service
metadata:
  name: tonic-pii-detection
  labels:
    app: tonic-pii-detection
spec:
  ports:
  - port: 7687
    targetPort: 7687
  selector:
    app: tonic-pii-detection
    {{- include "tonic.selectorLabels" . | nindent 4 }}
