apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tonic.fullname" . }}
  labels:
    app: tonic-queue
    {{- include "tonic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tonic-queue
      {{- include "tonic.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-queue
        {{- include "tonic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitMq.password }}
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitMq.user }}
        image: rabbitmq:3.6.6-management
        imagePullPolicy: ""
        name: tonic-queue
        ports:
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
