apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-pii-detection
  labels:
    app: tonic-pii-detection
    {{- include "tonic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.piiDetection.replicaCount }}
  selector:
    matchLabels:
      app: tonic-pii-detection
      {{- include "tonic.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-pii-detection
        {{- include "tonic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.piiDetection.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.piiDetection.environmentName }}
        image: {{ .Values.dockerRepoBaseUrl }}/tonic_pii_detection:latest
        imagePullPolicy: {{ .Values.piiDetection.image.pullPolicy }}
        name: tonic-pii-detection
        ports:
        - containerPort: 7687
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
