apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonic-worker
  name: tonic-worker
spec:
  replicas: {{ .Values.numberOfWorkers }}
  selector:
    matchLabels:
      app: tonic-worker
      {{- include "tonic.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-worker
        {{- include "tonic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: TONIC_AMPQP_URL
          value: amqp://{{ .Values.rabbitMq.user }}:{{ .Values.rabbitMq.password }}@tonic-queue:5672/
        - name: TONIC_DB_DATABASE
          value: {{ .Values.tonicdb.dbname }}
        - name: TONIC_DB_USERNAME
          value: {{ .Values.tonicdb.user }}
        - name: TONIC_DB_PASSWORD
          value: {{ .Values.tonicdb.password }}
        - name: TONIC_DB_PORT
          value: {{quote .Values.tonicdb.port }}
        - name: TONIC_DB_SSLMODE
          value: {{ .Values.tonicdb.sslMode }}
        - name: TONIC_DB_HOST
          value: {{ .Values.tonicdb.host }}
        - name: TONIC_PROCESS_PARALLELISM
          value: "1"
        - name: TONIC_TABLE_PARALLELISM
          value: "1"
        - name: TONIC_WRITE_PARALLELISM
          value: "1"
        - name: TONIC_STATISTICS_SEED
          value: {{quote .Values.tonicStatisticsSeed }}
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        - name: TONIC_PII_DETECTION_URL
          value: https://tonic-pii-detection:7687
        image: {{ .Values.dockerRepoBaseUrl }}/tonic_worker:latest
        imagePullPolicy: ""
        name: tonic-worker
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
